

################################# PROP2 #################################

  run_bt_executable_prop2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop2.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

  ros2oracleProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring && \
              /home/user1/monitoring-python-env/bin/python /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop2"

  groot_prop2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop2

  ros2monitorProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_prop2_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp2
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - fakeNavigation
      - fakeLocalizer
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop2
      - groot_prop2

################################# PROP3 #################################

  run_bt_executable_prop3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop3.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

  ros2oracleProp3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring && \
              /home/user1/monitoring-python-env/bin/python /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop3"

  groot_prop3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop3

  ros2monitorProp3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_prop3_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp3
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - fakeNavigation
      - fakeLocalizer
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop3
      - groot_prop3


################################# PROP4 #################################

  run_bt_executable_prop4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop4.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

  ros2oracleProp4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring && \
              /home/user1/monitoring-python-env/bin/python /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop4"

  groot_prop4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop4

  ros2monitorProp4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_prop4_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp4
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - fakeNavigation
      - fakeLocalizer
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop4
      - groot_prop4

################################# PROP5 #################################

  run_bt_executable_prop5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop5.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

  ros2oracleProp5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring && \
              /home/user1/monitoring-python-env/bin/python /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop5"

  groot_prop5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop5

  ros2monitorProp5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_prop5_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp5
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - fakeNavigation
      - fakeLocalizer
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop5
      - groot_prop5
