
x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - UC3_DIR=/home/user1/UC3/laboratory-tour/
    - XAUTHORITY=/home/user1/.Xauthority
    - QT_X11_NO_MITSHM=1
#    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user1/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
    - YARP_CLOCK=/clock
    - YARP_NAMESPACE=/root
    - ROS_DOMAIN_ID=47
    - CYCLONEDDS_URI=/home/user1/UC3/laboratory-tour/docker/cyclone_dds_settings.xml
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "/dev:/dev"

  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined


services:

# Images
  ros2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    build:
      dockerfile: Dockerfile
      context: .

  monitoring:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    build:
      dockerfile: Dockerfile.mon
      context: .


# containers
  terminator:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: terminator
    command: sh -c "yarp conf 172.17.0.1 10000; terminator --no-dbus"

  terminator_mon:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: terminator_mon
    command: sh -c "yarp conf 172.17.0.1 10000; terminator --no-dbus"

  yarpserver:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: yarpserver
    command: sh -c "yarp conf 172.17.0.1 10000; yarpserver"

  gazebo:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: gazebo
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              cd /usr/local/src/robot/tour-guide-robot/app/maps/SIM_GAM/ && \
              export GAZEBO_MODEL_PATH=/usr/local/src/robot/cer-sim/gazebo/ && \
              ros2 launch gazebo_ros gazebo.launch.py extra_gazebo_args:=-slibgazebo_yarp_clock.so world:=/usr/local/src/robot/tour-guide-robot/app/maps/SIM_GAM/GAM.world"
    depends_on:
      - yarpserver

  yarpmanager:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: yarpmanager
    command: bash -c "yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; yarpmanager --load_application /home/user1/UC3/laboratory-tour/launch/applications/Navigation_ROS2_R1_IROS.xml"
    depends_on:
      - yarpserver
      - gazebo


  fakeBattery:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: fakeBattery
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarprobotinterface --config /home/user1/UC3/laboratory-tour/src/components/fake_battery_component/robotinterface.xml"
    depends_on:
      - yarpserver
      - gazebo


  yarprun:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: yarprun
    command: bash -c "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/:/home/user1/Qt6.7.3/lib/ && \
              source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarp run --server /bt --log"
    depends_on:
      - yarpserver


  yarprun_console:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: yarprun_console
    command: bash -c "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/:/home/user1/Qt6.7.3/lib/ && \
              source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarp run --server /console --log"
    depends_on:
      - yarpserver

  yarplogger:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: yarplogger
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarplogger --start"
    depends_on:
      - yarpserver
      - gazebo 
      - yarpmanager

  environment:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: environment
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE};"
    depends_on:
      - terminator 
      - yarpserver
      - yarpmanager
      - fakeBattery
      - yarprun
      - yarprun_console
      - yarplogger
      - gazebo 

################################# COMPONENT AND SKILLS #################################
  run_components:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: run_components
    command: bash -c "sleep 2; source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarpmanager-console --application $${UC3_DIR}/launch/applications/convince_bt_components.xml --exit --run --connect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger


  run_skills_monitored:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: run_skills_monitored
    command: bash -c "sleep 2; source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarpmanager-console --application $${UC3_DIR}/launch/applications/convince_bt_skills_monitoredt.xml --exit --run --connect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger

  groot_propAll:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: groot_propAll
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_bt_executable_monitored

  run_bt_executable_monitored:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: run_bt_executable_monitored
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_monitored.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components


################################# MONITORING #################################
      
  ros2oracleProp1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleProp1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --port 8091 --online --dense --property prop1"

  ros2oracleProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --port 8092 --online --dense --property prop2"

  ros2oracleProp3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleProp3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --port 8093 --online --dense --property prop3"

  ros2oracleProp4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleProp4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --port 8094 --online --dense --property prop4"

  ros2oracleProp5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleProp5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --port 8095 --online --dense --property prop5"


  ros2oracleBatteryLevelFSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleBatteryLevelFSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/MOON/ModelMonitor/modeloracle && \
              mvn exec:java -Dexec.mainClass=io.github.convince.moon.Oracle -Dexec.args='--ioshape /home/user1/MOON/ModelMonitor/config_generator/BatteryLevelSkill_ioshape.json --statemachine /home/user1/UC3/laboratory-tour/model_scxml/BatteryLevelSkill.scxml --address 127.0.0.1:8081'"

  ros2oracleAlarmFSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleAlarmFSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/MOON/ModelMonitor/modeloracle && \
              mvn exec:java -Dexec.mainClass=io.github.convince.moon.Oracle -Dexec.args='--ioshape /home/user1/MOON/ModelMonitor/config_generator/AlarmSkill_ioshape.json --statemachine /home/user1/UC3/laboratory-tour/model_scxml/AlarmSkill.scxml --address 127.0.0.1:8082'"
  
  ros2oracleIsPoiDone1FSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleIsPoiDone1FSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/MOON/ModelMonitor/modeloracle && \
              mvn exec:java -Dexec.mainClass=io.github.convince.moon.Oracle -Dexec.args='--ioshape /home/user1/MOON/ModelMonitor/config_generator/IsPoiDone1Skill_ioshape.json --statemachine /home/user1/UC3/laboratory-tour/model_scxml/IsPoiDone1Skill.scxml --address 127.0.0.1:8083'"


  ros2oracleSetPoi1FSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2oracleSetPoi1FSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/MOON/ModelMonitor/modeloracle && \
              mvn exec:java -Dexec.mainClass=io.github.convince.moon.Oracle -Dexec.args='--ioshape /home/user1/MOON/ModelMonitor/config_generator/SetPoi1Skill_ioshape.json --statemachine /home/user1/UC3/laboratory-tour/model_scxml/SetPoi1Skill.scxml --address 127.0.0.1:8084'"

 
  ros2monitorProp1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorProp1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop1_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp1
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - gazebo


  ros2monitorProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop2_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp2
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - gazebo


  ros2monitorProp3:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorProp3
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop3_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp3
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - gazebo

  
  ros2monitorProp4:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorProp4
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop4_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp4
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - gazebo


  ros2monitorProp5:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorProp5
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop5_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp5
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - gazebo


  ros2monitorBatteryLevelFSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorBatteryLevelFSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_BatteryLevelSkill/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - ros2oracleBatteryLevelFSM
      - gazebo

  ros2monitorAlarmFSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorAlarmFSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_AlarmSkill/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - terminator
      - terminator_mon
      - yarpserver
      - yarprun
      - yarplogger
      - ros2oracleAlarmFSM
      - gazebo

  ros2monitorIsPoiDone1FSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorIsPoiDone1FSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_IsPoiDone1Skill/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - ros2oracleIsPoiDone1FSM
      - gazebo

  ros2monitorSetPoi1FSM:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_monitoring_iros
    <<: *base
    container_name: ros2monitorSetPoi1FSM
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd /home/user1/UC3/laboratory-tour/monitoring/monitor_SetPoi1Skill/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - terminator
      - yarpserver
      - yarprun
      - yarplogger
      - ros2oracleSetPoi1FSM
      - gazebo


  run_all_monitors:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: run_all 
    command: bash -c "echo 'done monitoring'"
    depends_on:
      - ros2monitorProp1
      - ros2monitorProp2
      - ros2monitorProp3
      - ros2monitorProp4
      - ros2monitorProp5
      - ros2monitorBatteryLevelFSM
      - ros2monitorAlarmFSM
      - ros2monitorIsPoiDone1FSM
      - ros2monitorSetPoi1FSM
      - groot_propAll

  run_oracles:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed_iros
    <<: *base
    container_name: run_oracles
    command: bash -c "echo 'done oracles'"
    depends_on:
      - ros2oracleProp1
      - ros2oracleProp2
      - ros2oracleProp3
      - ros2oracleProp4
      - ros2oracleProp5
      - ros2oracleBatteryLevelFSM
      - ros2oracleAlarmFSM
      - ros2oracleIsPoiDone1FSM
      - ros2oracleSetPoi1FSM


  