
x-base: &base
  environment:
    - DISPLAY=${DISPLAY}
    - UC3_DIR=/home/user1/UC3/laboratory-tour/
    - XAUTHORITY=/home/user1/.Xauthority
    - QT_X11_NO_MITSHM=1
#    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user1/1000/bus
    - LIBGL_ALWAYS_INDIRECT=0
    - YARP_COLORED_OUTPUT=1
    - YARP_CLOCK=/clock
    - YARP_NAMESPACE=/root
    - ROS_DOMAIN_ID=47
    - CYCLONEDDS_URI=/home/user1/UC3/laboratory-tour/docker/cyclone_dds_settings.xml
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "/etc/hosts:/etc/hosts"
    - "/dev:/dev"

  network_mode: host
  ipc: host
  pid: host
  privileged: true
  security_opt:
    - apparmor:unconfined


services:

# Images
  ros2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    build:
      dockerfile: Dockerfile
      context: .

# containers
  terminator:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: terminator
    command: sh -c "yarp conf 172.17.0.1 10000; terminator --no-dbus"

  yarpserver:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarpserver
    command: sh -c "yarp conf 172.17.0.1 10000; yarpserver"

  yarpclock:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarpclock
    command: sh -c "yarp conf 172.17.0.1 10000; yarp clock"
    depends_on:
      - yarpserver

  rosclock:
      image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
      <<: *base
      container_name: rosclock
      command: bash -c "source /opt/ros/iron/setup.bash && \
                source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
                source $${UC3_DIR}/install/setup.bash && \
                yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
                export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/; 
                ros2 run clock_component clock_component"


  gazebo:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: gazebo
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              cd /usr/local/src/robot/tour-guide-robot/app/maps/SIM_GAM/ && \
              export GAZEBO_MODEL_PATH=/usr/local/src/robot/cer-sim/gazebo/ && \
              ros2 launch gazebo_ros gazebo.launch.py extra_gazebo_args:=-slibgazebo_yarp_clock.so world:=/usr/local/src/robot/tour-guide-robot/app/maps/SIM_GAM/GAM.world"
    depends_on:
      - yarpserver
      - rosclock

  yarpmanager:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarpmanager
    command: bash -c "yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; yarpmanager"
    depends_on:
      - yarpserver
      - gazebo


  fakeBattery:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: fakeBattery
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              echo $${UC3_DIR} && \
              yarprobotinterface --config $${UC3_DIR}/src/components/fake_battery_component/robotinterface.xml"
    depends_on:
      - yarpserver
      - gazebo

  mapServer:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: mapServer
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarprobotinterface --context navigation2 --from mapServer.ini"
    depends_on:
      - yarpserver

  localization:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: localization
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarprobotinterface --context navigation2 --from localizationROS2.ini --init_map gam_sim_real"
    depends_on:
      - yarpserver

  navigator:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: navigator
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarprobotinterface --context navigation2 --from navigator2D.ini"
    depends_on:
      - yarpserver


  yarprun:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarprun
    command: bash -c "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/:/home/user1/Qt6.7.3/lib/ && \
              source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarp run --server /bt --log"
    depends_on:
      - yarpserver


  yarprun_console:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarprun_console
    command: bash -c "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/src/robot/yarp/build/lib/:/home/user1/Qt6.7.3/lib/ && \
              source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarp run --server /console --log"
    depends_on:
      - yarpserver

  yarplogger:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: yarplogger
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarplogger --start"
    depends_on:
      - yarpserver
      - gazebo 
      - yarpmanager

  environment:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: environment
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE};"
    depends_on:
      - terminator 
      - yarpserver
      - yarpclock
      - rosclock
      - yarpmanager
      - fakeBattery
      - yarprun
      - yarprun_console
      - yarplogger
      - gazebo 
      - mapServer
      - localization
      - navigator

################################# COMPONENT AND SKILLS #################################
  run_components:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_components
    command: bash -c "sleep 2; source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarpmanager-console --application $${UC3_DIR}/launch/applications/convince_bt_components.xml --exit --run --connect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger

  run_skills:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_skills
    command: bash -c "sleep 2; source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              yarpmanager-console --application $${UC3_DIR}/launch/applications/convince_bt_skills.xml --exit --run --connect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger

################################# PROP1 #################################
  run_bt_executable_prop1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop1.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

      
  ros2oracleProp1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop1"

  
  groot_prop1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop1

  ros2monitorProp1:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp1
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop1_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp1
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop1
      - groot_prop1
      - gazebo

    
################################# PROP2 #################################

  run_bt_executable_prop2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: run_bt_executable_prop2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              yarp conf 172.17.0.1 10000; yarp wait $${YARP_NAMESPACE}; \
              ros2 run bt_executable bt_executable $${UC3_DIR}/src/behavior_tree/BT/Policy_prop2.xml"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills

  ros2oracleProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2oracleProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}//install/setup.bash && \
              cd $${UC3_DIR}//monitoring && \
              python3 /home/user1/ROSMonitoring/oracle/TLOracle/oracle.py --online --dense --property prop2"

  groot_prop2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: groot_prop2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source /usr/local/src/robot/yarp-devices-ros2/ros2_interfaces_ws/install/setup.bash && \
              source $${UC3_DIR}//install/setup.bash && \
              /home/user1/Groot/build/Groot --mode monitor --autoconnect"
    depends_on:
      - yarpserver
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop2

  ros2monitorProp2:
    image: ste93/convince:qt_6.7.3_ubuntu22.04_iron_stable_sim_completed
    <<: *base
    container_name: ros2monitorProp2
    command: bash -c "source /opt/ros/iron/setup.bash && \
              source $${UC3_DIR}/install/setup.bash && \
              cd $${UC3_DIR}/monitoring/monitor_prop2_ws/src/ && \
              source install/setup.bash && \
              ros2 launch monitor/launch/monitor.launch"
    depends_on:
      - ros2oracleProp2
      - terminator
      - yarpserver
      - yarpclock
      - rosclock
      - fakeBattery
      - mapServer
      - localization
      - navigator
      - yarprun
      - yarplogger
      - run_components
      - run_skills
      - run_bt_executable_prop2
      - groot_prop2